# MARK: General

disabled_rules:
  - todo
  - trailing_comma

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_type_annotation
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

analyzer_rules:
   - unused_declaration
   - unused_import

excluded:
  - .build
  - Carthage
  - fastlane
  - Packages
  - Pods
  - R.generated.swift
  - Scripts
  - Supporting
  - Tuist
  - vendor

# MARK: Individual Rules

empty_count:
  severity: warning

file_length:
  error: 1000
  warning: 700

force_cast: error

function_body_length:
  error: 150
  warning: 100

identifier_name:
  excluded:
    - id

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
  error: 300
  warning: 200

trailing_whitespace:
  ignores_empty_lines: true

type_body_length:
  error: 900
  warning: 600

vertical_whitespace:
  max_empty_lines: 2

# MARK: Custom Rules

custom_rules:

  # https://github.com/brandenr/swiftlintconfig
  comments_space:
    name: "Space after comment"
    regex: "(^ *//\\w+)"
    message: "There should be a space after //"
    severity: warning

  # https://github.com/IBM-Swift/Package-Builder
  double_space:
    include: "*.swift"
    name: "Double space"
    regex: "([a-z,A-Z] \\s+)"
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning

  # https://github.com/Twigz/Game
  force_https:
    name: "Force HTTPS over HTTP"
    regex: "((?i)http(?!s))"
    match_kinds: string
    message: "HTTPS should be favored over HTTP"
    severity: warning
